/* This file was generated by syncqt. */
#ifndef QT_QTSENSORS_VERSION_H
#define QT_QTSENSORS_VERSION_H

#define QTSENSORS_VERSION_STR "5.13.0"

#define QTSENSORS_VERSION 0x050D00

#endif // QT_QTSENSORS_VERSION_H
