/* This file was generated by syncqt. */
#ifndef QT_QT3DQUICK_VERSION_H
#define QT_QT3DQUICK_VERSION_H

#define QT3DQUICK_VERSION_STR "5.13.0"

#define QT3DQUICK_VERSION 0x050D00

#endif // QT_QT3DQUICK_VERSION_H
