/* This file was generated by syncqt. */
#ifndef QT_QTSCRIPT_VERSION_H
#define QT_QTSCRIPT_VERSION_H

#define QTSCRIPT_VERSION_STR "5.13.0"

#define QTSCRIPT_VERSION 0x050D00

#endif // QT_QTSCRIPT_VERSION_H
