/* This file was generated by syncqt. */
#ifndef QT_QTWIDGETS_VERSION_H
#define QT_QTWIDGETS_VERSION_H

#define QTWIDGETS_VERSION_STR "5.13.0"

#define QTWIDGETS_VERSION 0x050D00

#endif // QT_QTWIDGETS_VERSION_H
